# Platform-independent file operation commands
!ifdef __UNIX__
MKDIR = mkdir -p
COPY_FILE = cp -rf
RM_FILE = rm -rf
RM_DIR = rm -rf
!else
MKDIR = MD
COPY_FILE = COPY /Y
RM_FILE = DEL /F /Q
RM_DIR = RD /S /Q
!endif

####### Compiler, flags and options

SYSTEM_DOS16 = DOS
SYSTEM_DOS32 = DOS4G

CC_DOS16 = wcl -cc
CC_DOS32 = wcl386 -cc

CPPFLAGS = -I$(INCLUDE_DIR) -DWATCOM

CFLAGS = -we -w4 -zq -ml

CFLAGS_OPTIMIZE_BASIC = -oneatx -oh -ei -zp8

CFLAGS_OPTIMIZE_DOS16 = $(CFLAGS_OPTIMIZE_BASIC) -fpi87
CFLAGS_OPTIMIZE_DOS16_8086 = $(CFLAGS_OPTIMIZE_DOS16) -0
CFLAGS_OPTIMIZE_DOS16_186 = $(CFLAGS_OPTIMIZE_DOS16) -1
CFLAGS_OPTIMIZE_DOS16_286 = $(CFLAGS_OPTIMIZE_DOS16) -2 -fp2
CFLAGS_OPTIMIZE_DOS16_386 = $(CFLAGS_OPTIMIZE_DOS16) -3 -fp3
CFLAGS_OPTIMIZE_DOS16_486 = $(CFLAGS_OPTIMIZE_DOS16) -4 -fp3
CFLAGS_OPTIMIZE_DOS16_PENTIUM = $(CFLAGS_OPTIMIZE_DOS16) -5 -fp5
CFLAGS_OPTIMIZE_DOS16_PENTIUM_PRO = $(CFLAGS_OPTIMIZE_DOS16) -6 -fp6

CFLAGS_OPTIMIZE_DOS32_386 = $(CFLAGS_OPTIMIZE_BASIC) -3 -fp3
CFLAGS_OPTIMIZE_DOS32_486 = $(CFLAGS_OPTIMIZE_BASIC) -4 -fp3
CFLAGS_OPTIMIZE_DOS32_PENTIUM = $(CFLAGS_OPTIMIZE_BASIC) -5 -fp5
CFLAGS_OPTIMIZE_DOS32_PENTIUM_PRO = $(CFLAGS_OPTIMIZE_BASIC) -6 -fp6

CFLAGS_DOS16 = $(CFLAGS) -l=$(SYSTEM_DOS16) $(CFLAGS_OPTIMIZE_DOS16_8086)
CFLAGS_DOS32 = $(CFLAGS) -l=$(SYSTEM_DOS32) $(CFLAGS_OPTIMIZE_DOS32_386)

LIBUTIL = wlib

LIB_DIR = lib		# Target library directory

LIB_DOS16_DIR = $(LIB_DIR)/dos16
LIB_DOS32_DIR = $(LIB_DIR)/dos32

LIB_DOS16_TARGET = $(LIB_DOS16_DIR)/BDGL.lib
LIB_DOS32_TARGET = $(LIB_DOS32_DIR)/BDGL.lib
