EXAMPLES_OBJ_DOS16_DIR = $(OBJ_DOS16_DIR)$(SEP)examples
EXAMPLES_OBJ_DOS32_DIR = $(OBJ_DOS32_DIR)$(SEP)examples

EXAMPLES_BIN_DIR = bin$(SEP)examples
EXAMPLES_BIN_DOS16_DIR = $(EXAMPLES_BIN_DIR)$(SEP)dos16
EXAMPLES_BIN_DOS32_DIR = $(EXAMPLES_BIN_DIR)$(SEP)dos32

$(EXAMPLES_OBJ_DOS16_DIR)/bmp.obj : $(EXAMPLES_SRC_DIR)/bmp.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS16_DIR)
	$(C_TO_OBJ16)

$(EXAMPLES_OBJ_DOS32_DIR)/bmp.obj : $(EXAMPLES_SRC_DIR)/bmp.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS32_DIR)
	$(C_TO_OBJ32)

$(EXAMPLES_OBJ_DOS16_DIR)/hello.obj : $(EXAMPLES_SRC_DIR)/hello.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS16_DIR)
	$(C_TO_OBJ16)

$(EXAMPLES_OBJ_DOS32_DIR)/hello.obj : $(EXAMPLES_SRC_DIR)/hello.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS32_DIR)
	$(C_TO_OBJ32)

$(EXAMPLES_OBJ_DOS16_DIR)/keys.obj : $(EXAMPLES_SRC_DIR)/keys.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS16_DIR)
	$(C_TO_OBJ16)

$(EXAMPLES_OBJ_DOS32_DIR)/keys.obj : $(EXAMPLES_SRC_DIR)/keys.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS32_DIR)
	$(C_TO_OBJ32)

$(EXAMPLES_OBJ_DOS16_DIR)/mouse.obj : $(EXAMPLES_SRC_DIR)/mouse.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS16_DIR)
	$(C_TO_OBJ16)

$(EXAMPLES_OBJ_DOS32_DIR)/mouse.obj : $(EXAMPLES_SRC_DIR)/mouse.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS32_DIR)
	$(C_TO_OBJ32)

$(EXAMPLES_OBJ_DOS16_DIR)/stars.obj : $(EXAMPLES_SRC_DIR)/stars.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS16_DIR)
	$(C_TO_OBJ16)

$(EXAMPLES_OBJ_DOS32_DIR)/stars.obj : $(EXAMPLES_SRC_DIR)/stars.c
	@$(MKDIR_CMD) $(EXAMPLES_OBJ_DOS32_DIR)
	$(C_TO_OBJ32)

$(EXAMPLES_BIN_DOS16_DIR)/bmp.exe : $(EXAMPLES_OBJ_DOS16_DIR)/bmp.obj $(LIB_DOS16_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS16_DIR)
	$(LD) system dos name $@ file $[@ library $(LIB_DOS16_TARGET)
	$(COPY_CMD) $(EXAMPLES_SRC_DIR)$(SEP)IMAGE.BMP $(EXAMPLES_BIN_DOS16_DIR)

$(EXAMPLES_BIN_DOS32_DIR)/bmp.exe : $(EXAMPLES_OBJ_DOS32_DIR)/bmp.obj $(LIB_DOS32_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS32_DIR)
	$(LD) system dos4g name $* file $[@ library $(LIB_DOS32_TARGET)
	$(COPY_CMD) $(EXAMPLES_SRC_DIR)$(SEP)IMAGE.BMP $(EXAMPLES_BIN_DOS32_DIR)

$(EXAMPLES_BIN_DOS16_DIR)/hello.exe : $(EXAMPLES_OBJ_DOS16_DIR)/hello.obj $(LIB_DOS16_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS16_DIR)
	$(LD) system dos name $@ file $[@ library $(LIB_DOS16_TARGET)

$(EXAMPLES_BIN_DOS32_DIR)/hello.exe : $(EXAMPLES_OBJ_DOS32_DIR)/hello.obj $(LIB_DOS32_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS32_DIR)
	$(LD) system dos4g name $* file $[@ library $(LIB_DOS32_TARGET)

$(EXAMPLES_BIN_DOS16_DIR)/keys.exe : $(EXAMPLES_OBJ_DOS16_DIR)/keys.obj $(LIB_DOS16_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS16_DIR)
	$(LD) system dos name $@ file $[@ library $(LIB_DOS16_TARGET)

$(EXAMPLES_BIN_DOS32_DIR)/keys.exe : $(EXAMPLES_OBJ_DOS32_DIR)/keys.obj $(LIB_DOS32_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS32_DIR)
	$(LD) system dos4g name $* file $[@ library $(LIB_DOS32_TARGET)

$(EXAMPLES_BIN_DOS16_DIR)/mouse.exe : $(EXAMPLES_OBJ_DOS16_DIR)/mouse.obj $(LIB_DOS32_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS16_DIR)
	$(LD) system dos name $@ file $[@ library $(LIB_DOS16_TARGET)

$(EXAMPLES_BIN_DOS32_DIR)/mouse.exe : $(EXAMPLES_OBJ_DOS32_DIR)/mouse.obj $(LIB_DOS16_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS32_DIR)
	$(LD) system dos4g name $* file $[@ library $(LIB_DOS32_TARGET)

$(EXAMPLES_BIN_DOS16_DIR)/stars.exe : $(EXAMPLES_OBJ_DOS16_DIR)/stars.obj $(LIB_DOS32_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS16_DIR)
	$(LD) system dos name $@ file $[@ library $(LIB_DOS16_TARGET)

$(EXAMPLES_BIN_DOS32_DIR)/stars.exe : $(EXAMPLES_OBJ_DOS32_DIR)/stars.obj $(LIB_DOS16_TARGET)
	@$(MKDIR_CMD) $(EXAMPLES_BIN_DOS32_DIR)
	$(LD) system dos4g name $* file $[@ library $(LIB_DOS32_TARGET)


EXAMPLES_DOS16 = &
  $(EXAMPLES_BIN_DOS16_DIR)$(SEP)bmp.exe &
  $(EXAMPLES_BIN_DOS16_DIR)$(SEP)hello.exe &
  $(EXAMPLES_BIN_DOS16_DIR)$(SEP)keys.exe &
  $(EXAMPLES_BIN_DOS16_DIR)$(SEP)mouse.exe &
  $(EXAMPLES_BIN_DOS16_DIR)$(SEP)stars.exe


EXAMPLES_DOS32 = &
  $(EXAMPLES_BIN_DOS32_DIR)$(SEP)bmp.exe &
  $(EXAMPLES_BIN_DOS32_DIR)$(SEP)hello.exe &
  $(EXAMPLES_BIN_DOS32_DIR)$(SEP)keys.exe &
  $(EXAMPLES_BIN_DOS32_DIR)$(SEP)mouse.exe &
  $(EXAMPLES_BIN_DOS32_DIR)$(SEP)stars.exe

